#!/usr/bin/env tsx
/**
 * gen-shard-config.ts
 *
 * Generates a per-shard Playwright config file (playwright.shard.config.ts)
 * that extends the base playwright.config.ts but overrides `testMatch` to
 * contain only the spec files assigned to the given shard index by the LPT
 * bin-packer (gen-shards.ts).
 *
 * - Emits a warning if any baseline file no longer exists on disk.
 * - The generated file is gitignored; it is produced fresh on each CI run.
 * - --selected-files=<path>, when given and readable, LPT-assigns only that
 *   subset (pr-tia-8) instead of the full discoverSpecFiles() suite — MUST
 *   be passed identically to every --shard-index invocation in a CI loop,
 *   since the LPT bin-packing must be reproduced identically across calls
 *   for shard assignments to be non-overlapping.
 *
 * Usage (from repo root):
 *   npm run e2e:timing:gen-config -- --shard-index=0 --total-shards=4
 *   npm run e2e:timing:gen-config -- --shard-index=0 --total-shards=2 --selected-files=/tmp/tia-selection.json
 *
 *
 */

import path from 'node:path';
import fs from 'node:fs';
import {
  readTimingBaseline,
  readSelectedFiles,
  discoverSpecFiles,
  lptAssign,
  TIMING_BASELINE_FILENAME,
  DEFAULT_FALLBACK_MS,
  type FileDuration,
} from '../framework/reporting/timing-utils.js';

const E2E_DIR = path.resolve(process.cwd(), 'qa/e2e');
const BASELINE_PATH = path.join(E2E_DIR, TIMING_BASELINE_FILENAME);
const FUNCTIONAL_TESTS_DIR = path.join(E2E_DIR, 'tests/apps/minicrm/functional');

// ── CLI args ──────────────────────────────────────────────────────────────────

interface CliArgs {
  shardIndex: number;
  totalShards: number;
  selectedFilesPath: string | undefined;
}

/**
 * Splits argv into this script's options.
 *
 * Takes argv as a parameter and returns errors rather than reading
 * `process.argv` and calling `process.exit` inline — the latter is untestable
 * by construction, which is why the `=`-preserving split below went unpinned
 * for as long as it did. `main()` does the exiting.
 */
export function parseGenShardConfigArgs(
  argv: readonly string[],
):
  | { shardIndex: number; totalShards: number; selectedFilesPath: string | undefined; error: null }
  | { error: string } {
  const idxArg = argv.find((a) => a.startsWith('--shard-index='));
  const totalArg = argv.find((a) => a.startsWith('--total-shards='));

  if (!idxArg || !totalArg) {
    return {
      error: '[gen-shard-config] Usage: gen-shard-config.ts --shard-index=N --total-shards=M',
    };
  }

  // /^\d+$/ before parseInt, not isNaN after it. parseInt('2x') → 2 and
  // parseInt('4.9') → 4, both of which pass every range check below and produce
  // a REAL config for the wrong shard — so a typo'd index silently runs a
  // different set of specs than the one asked for, and the specs in the
  // intended shard never run at all. Same reject-don't-coerce rule as
  // verify-test-attestation.ts's --max-age-minutes and
  // qa/scripts/merge-junit-results.ts's --expected-files.
  const idxRaw = idxArg.split('=').slice(1).join('=');
  const totalRaw = totalArg.split('=').slice(1).join('=');
  if (!/^\d+$/.test(idxRaw) || !/^\d+$/.test(totalRaw)) {
    return {
      error: `[gen-shard-config] Invalid args: --shard-index and --total-shards require non-negative integers, got "${idxRaw}" and "${totalRaw}".`,
    };
  }

  const shardIndex = Number(idxRaw);
  const totalShards = Number(totalRaw);

  if (totalShards < 1 || shardIndex >= totalShards) {
    return { error: '[gen-shard-config] Invalid args: shardIndex must be 0..(totalShards-1).' };
  }

  const selectedFilesArg = argv.find((a) => a.startsWith('--selected-files='));
  // .slice(1).join('=') rather than [1], so a path containing '=' survives.
  // Same reasoning as gen-shards.ts's copy of this flag.
  const selectedFilesPath = selectedFilesArg?.split('=').slice(1).join('=');

  return { shardIndex, totalShards, selectedFilesPath, error: null };
}

function parseArgs(): CliArgs {
  const parsed = parseGenShardConfigArgs(process.argv);
  if (parsed.error !== null) {
    process.stderr.write(`${parsed.error}\n`);
    process.exit(1);
  }
  return parsed;
}

// ── Config file generation ────────────────────────────────────────────────────

function generateShardConfig(
  assignedFiles: string[],
  shardIndex: number,
  totalShards: number,
): string {
  // testMatch entries must be absolute paths. Playwright resolves relative paths
  // in testMatch against the config file location (qa/e2e/), not the repo root,
  // so repo-root-relative paths would be wrong. Absolute paths are portable
  // across any working directory.
  const testMatchEntries = assignedFiles
    .map((f) => `  '${path.resolve(process.cwd(), f).replace(/\\/g, '/')}'`)
    .join(',\n');

  return (
    `// Auto-generated by gen-shard-config.ts — DO NOT EDIT\n` +
    `// Shard ${shardIndex} of ${totalShards} (0-indexed)\n` +
    `// Regenerate with: npm run e2e:timing:gen-config -- --shard-index=${shardIndex} --total-shards=${totalShards}\n` +
    `\n` +
    `import { defineConfig } from '@playwright/test';\n` +
    `import baseConfig from './playwright.config.js';\n` +
    `\n` +
    `export default defineConfig({\n` +
    `  ...baseConfig,\n` +
    `  testMatch: [\n` +
    `${testMatchEntries}\n` +
    `  ],\n` +
    `});\n`
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const { shardIndex, totalShards, selectedFilesPath } = parseArgs();

  const baseline = readTimingBaseline(BASELINE_PATH);
  const fallbackMs = baseline?.fallbackMs ?? DEFAULT_FALLBACK_MS;

  if (!baseline) {
    process.stderr.write(
      `[gen-shard-config] WARN: ${BASELINE_PATH} not found. ` +
        `All files will use fallback duration of ${fallbackMs}ms.\n`,
    );
  }

  const selectedFiles = readSelectedFiles(selectedFilesPath);
  if (selectedFilesPath && !selectedFiles) {
    process.stderr.write(
      `[gen-shard-config] WARN: --selected-files="${selectedFilesPath}" was given but could not be read/parsed — falling back to the full discoverSpecFiles() suite.\n`,
    );
  }
  const specFiles = selectedFiles ?? discoverSpecFiles(FUNCTIONAL_TESTS_DIR);
  if (selectedFiles) {
    process.stderr.write(
      `[gen-shard-config] Using TIA-selected subset: ${specFiles.length} file(s) from ${selectedFilesPath}.\n`,
    );
  }

  if (specFiles.length === 0) {
    process.stderr.write(`[gen-shard-config] No spec files found under ${FUNCTIONAL_TESTS_DIR}.\n`);
    process.exit(1);
  }

  // Warn about baseline entries that no longer exist on disk.
  if (baseline) {
    for (const file of Object.keys(baseline.files)) {
      const absPath = path.resolve(process.cwd(), file);
      if (!fs.existsSync(absPath)) {
        process.stderr.write(
          `[gen-shard-config] WARN: "${file}" is in the baseline but no longer exists on disk.\n`,
        );
      }
    }
  }

  const fileDurations: FileDuration[] = specFiles.map((file) => {
    const entry = baseline?.files[file];
    if (!entry) {
      return { file, estimatedMs: fallbackMs };
    }
    return { file, estimatedMs: entry.medianMs };
  });

  const assignment = lptAssign(fileDurations, totalShards);
  const shardFiles = assignment[shardIndex] ?? [];

  const outputPath = path.join(E2E_DIR, `playwright.shard.${shardIndex}.config.ts`);
  const configContent = generateShardConfig(shardFiles, shardIndex, totalShards);
  fs.writeFileSync(outputPath, configContent, 'utf-8');

  process.stdout.write(
    `[gen-shard-config] Wrote ${outputPath}\n` +
      `  Shard ${shardIndex}/${totalShards}: ${shardFiles.length} files\n`,
  );
}

// Direct-invocation guard — see gen-shards.ts's copy for why, including why
// this uses the endsWith form rather than the server scripts' exact equality. Without it,
// importing this module to unit-test parseGenShardConfigArgs runs main(), which
// process.exit(1)s on the absent --shard-index and kills the test worker.
if (process.argv[1] && path.resolve(process.argv[1]).endsWith('gen-shard-config.ts')) {
  main();
}
