#!/usr/bin/env tsx
/**
 * gen-shard-config.ts
 *
 * Generates a per-shard Playwright config file (playwright.shard.config.ts)
 * that extends the base playwright.config.ts but overrides `testMatch` to
 * contain only the spec files assigned to the given shard index by the LPT
 * bin-packer (gen-shards.ts).
 *
 * - Emits a warning if any baseline file no longer exists on disk.
 * - The generated file is gitignored; it is produced fresh on each CI run.
 *
 * Usage (from repo root):
 *   npm run e2e:timing:gen-config -- --shard-index=0 --total-shards=4
 *
 * MINCRM-549
 */

import path from 'node:path';
import fs from 'node:fs';
import {
  readTimingBaseline,
  TIMING_BASELINE_FILENAME,
  DEFAULT_FALLBACK_MS,
} from '../framework/reporting/timing-utils.js';

const E2E_DIR = path.resolve(process.cwd(), 'qa/e2e');
const BASELINE_PATH = path.join(E2E_DIR, TIMING_BASELINE_FILENAME);
const FUNCTIONAL_TESTS_DIR = path.join(E2E_DIR, 'tests/apps/minicrm/functional');
const OUTPUT_CONFIG_PATH = path.join(E2E_DIR, 'playwright.shard.config.ts');

// ── CLI args ──────────────────────────────────────────────────────────────────

interface CliArgs {
  shardIndex: number;
  totalShards: number;
}

function parseArgs(): CliArgs {
  const idxArg = process.argv.find((a) => a.startsWith('--shard-index='));
  const totalArg = process.argv.find((a) => a.startsWith('--total-shards='));

  if (!idxArg || !totalArg) {
    process.stderr.write(
      `[gen-shard-config] Usage: gen-shard-config.ts --shard-index=N --total-shards=M\n`,
    );
    process.exit(1);
  }

  const shardIndex = parseInt(idxArg.split('=')[1] ?? '', 10);
  const totalShards = parseInt(totalArg.split('=')[1] ?? '', 10);

  if (
    isNaN(shardIndex) ||
    isNaN(totalShards) ||
    shardIndex < 0 ||
    totalShards < 1 ||
    shardIndex >= totalShards
  ) {
    process.stderr.write(
      `[gen-shard-config] Invalid args: shardIndex must be 0..(totalShards-1).\n`,
    );
    process.exit(1);
  }

  return { shardIndex, totalShards };
}

// ── Spec file discovery (mirrors gen-shards.ts) ───────────────────────────────

function discoverSpecFiles(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...discoverSpecFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.spec.ts')) {
      results.push(path.relative(process.cwd(), fullPath));
    }
  }
  return results.sort();
}

// ── LPT bin-packing (mirrors gen-shards.ts) ──────────────────────────────────

interface FileDuration {
  file: string;
  estimatedMs: number;
}

function lptAssign(files: FileDuration[], workerCount: number): string[][] {
  const sorted = [...files].sort((a, b) => b.estimatedMs - a.estimatedMs);
  const buckets: string[][] = Array.from({ length: workerCount }, () => []);
  const totals: number[] = Array.from({ length: workerCount }, () => 0);

  for (const { file, estimatedMs } of sorted) {
    let minIdx = 0;
    for (let i = 1; i < workerCount; i++) {
      if ((totals[i] as number) < (totals[minIdx] as number)) minIdx = i;
    }
    (buckets[minIdx] as string[]).push(file);
    (totals[minIdx] as number) += estimatedMs;
  }

  return buckets;
}

// ── Config file generation ────────────────────────────────────────────────────

function generateShardConfig(
  assignedFiles: string[],
  shardIndex: number,
  totalShards: number,
): string {
  // Paths in testMatch must be absolute or relative to the config file location.
  // We emit repo-root-relative paths and instruct Playwright to resolve them from CWD.
  const testMatchEntries = assignedFiles.map((f) => `  '${f.replace(/\\/g, '/')}'`).join(',\n');

  return (
    `// Auto-generated by gen-shard-config.ts — DO NOT EDIT (MINCRM-549)\n` +
    `// Shard ${shardIndex} of ${totalShards} (0-indexed)\n` +
    `// Regenerate with: npm run e2e:timing:gen-config -- --shard-index=${shardIndex} --total-shards=${totalShards}\n` +
    `\n` +
    `import { defineConfig } from '@playwright/test';\n` +
    `import baseConfig from './playwright.config.js';\n` +
    `\n` +
    `export default defineConfig({\n` +
    `  ...baseConfig,\n` +
    `  testMatch: [\n` +
    `${testMatchEntries}\n` +
    `  ],\n` +
    `});\n`
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const { shardIndex, totalShards } = parseArgs();

  const baseline = readTimingBaseline(BASELINE_PATH);
  const fallbackMs = baseline?.fallbackMs ?? DEFAULT_FALLBACK_MS;

  if (!baseline) {
    process.stderr.write(
      `[gen-shard-config] WARN: ${BASELINE_PATH} not found. ` +
        `All files will use fallback duration of ${fallbackMs}ms.\n`,
    );
  }

  const specFiles = discoverSpecFiles(FUNCTIONAL_TESTS_DIR);

  if (specFiles.length === 0) {
    process.stderr.write(`[gen-shard-config] No spec files found under ${FUNCTIONAL_TESTS_DIR}.\n`);
    process.exit(1);
  }

  // Warn about baseline entries that no longer exist on disk.
  if (baseline) {
    for (const file of Object.keys(baseline.files)) {
      const absPath = path.resolve(process.cwd(), file);
      if (!fs.existsSync(absPath)) {
        process.stderr.write(
          `[gen-shard-config] WARN: "${file}" is in the baseline but no longer exists on disk.\n`,
        );
      }
    }
  }

  const fileDurations: FileDuration[] = specFiles.map((file) => {
    const entry = baseline?.files[file];
    if (!entry) {
      return { file, estimatedMs: fallbackMs };
    }
    return { file, estimatedMs: entry.medianMs };
  });

  const assignment = lptAssign(fileDurations, totalShards);
  const shardFiles = assignment[shardIndex] ?? [];

  const configContent = generateShardConfig(shardFiles, shardIndex, totalShards);
  fs.writeFileSync(OUTPUT_CONFIG_PATH, configContent, 'utf-8');

  process.stdout.write(
    `[gen-shard-config] Wrote ${OUTPUT_CONFIG_PATH}\n` +
      `  Shard ${shardIndex}/${totalShards}: ${shardFiles.length} files\n`,
  );
}

main();
