'use strict';

/**
 * Migration 084: Document the unique constraint assumption on gdpr_deletion_log. (MINCRM-517)
 *
 * Migration 050 creates a UNIQUE index on (record_type, record_id) in gdpr_deletion_log.
 * This implies that any given record can appear in the erasure log at most once. That is
 * safe today because every record_id in MiniCRM is a UUID generated by gen_random_uuid()
 * at row-creation time — a re-import of a previously erased record always produces a new
 * UUID and therefore a new record_id that has no history in the log.
 *
 * Risk scenario: if a future integration assigns deterministic external IDs to records
 * (e.g. syncing from a third-party system that reuses its own primary keys), a re-import
 * of an erased record would produce a row with the same record_id. A subsequent erasure
 * request for that re-imported record would fail with a unique constraint violation
 * (pg error 23505) because the original erasure entry still exists.
 *
 * No schema change is made here. This migration adds table and column comments so the
 * assumption is visible to anyone inspecting the schema directly, without needing to read
 * application code or this migration header.
 *
 * If deterministic external IDs are ever introduced, the constraint must be revisited.
 * Options at that point include: relaxing to a non-unique index and making record_id +
 * requested_at the natural key, or adding a generation/version column to allow multiple
 * erasure entries per logical record identity.
 */

/** @type {import('node-pg-migrate').ColumnDefinitions | undefined} */
exports.shorthands = undefined;

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.up = (pgm) => {
  pgm.sql(`
    COMMENT ON TABLE gdpr_deletion_log IS
      'Append-only log of GDPR Art. 17 erasure requests (one row per erased record). '
      'The UNIQUE index on (record_type, record_id) is safe because all record_id values '
      'are UUIDs generated by gen_random_uuid() at row-creation time — re-imports always '
      'receive a new UUID. If deterministic external IDs are ever introduced this constraint '
      'must be revisited. See migration 084 for full rationale. (MINCRM-517)';
  `);

  pgm.sql(`
    COMMENT ON COLUMN gdpr_deletion_log.record_id IS
      'UUID of the erased record. References the PK of the entity identified by record_type. '
      'No FK constraint — the referenced row will have been hard-deleted before or during erasure. '
      'UNIQUE constraint assumption: safe only while all record IDs are gen_random_uuid() UUIDs. '
      'See migration 084 if deterministic external IDs are introduced.';
  `);
};

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.down = (pgm) => {
  pgm.sql(`COMMENT ON COLUMN gdpr_deletion_log.record_id IS NULL;`);
  pgm.sql(`COMMENT ON TABLE gdpr_deletion_log IS NULL;`);
};
