'use strict';

/**
 * Migration 085: Document the polymorphic FK pattern on tables that use
 * (record_type, record_id) or (entity_type, entity_id) without a real FK
 * constraint.
 *
 * Five tables store a reference to one of several parent entity types using a
 * type discriminator column plus a UUID. Because PostgreSQL FK constraints can
 * only reference a single parent table, no FK constraint is possible here —
 * the reference integrity is enforced at the application layer instead.
 *
 * Affected tables and their parent entity sets:
 *   attachments          record_type ∈ {contact, account, deal, lead}
 *   custom_field_values  record_id references the entity identified by
 *                        custom_field_definitions.entity_type ∈ {contact, account, deal}
 *   notes                entity_type ∈ {contact, account, deal, lead}
 *   gdpr_deletion_log    record_type is any entity type that can be erased
 *   audit_log            record_type — already documented in migration 076
 *
 * Orphan accumulation: when a parent entity is hard-deleted, rows in the
 * polymorphic tables pointing at it are not automatically removed. The
 * application is responsible for deleting dependent rows before or during the
 * parent delete. For tables where retention is intentional (audit_log,
 * gdpr_deletion_log), no cleanup is performed — the rows are retained by design.
 *
 * audit_log: already has a table comment from migration 076; not touched here.
 */

/** @type {import('node-pg-migrate').ColumnDefinitions | undefined} */
exports.shorthands = undefined;

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.up = (pgm) => {
  pgm.sql(`
    COMMENT ON TABLE attachments IS
      'File attachment metadata for CRM entity records. '
      'record_type + record_id form a polymorphic reference — no FK constraint exists '
      'because PostgreSQL FKs cannot span multiple parent tables. '
      'Valid record_type values: ''contact'', ''account'', ''deal'', ''lead'' (extended in migration 047). '
      'Orphan cleanup is the application''s responsibility: rows whose record_id no longer '
      'exists in the referenced entity table should be deleted when the parent is removed. '
      'The physical file (storage_key) must be deleted from object storage before or '
      'alongside the row. See CLAUDE.md — Polymorphic FK Pattern. (MINCRM-510)';
  `);

  pgm.sql(`
    COMMENT ON TABLE custom_field_values IS
      'Values for admin-defined custom fields on CRM entity records. '
      'record_id is a polymorphic reference to the entity row identified by the '
      'associated custom_field_definitions.entity_type — no FK constraint is possible '
      'because the parent table varies per definition. '
      'Valid entity_type values (on custom_field_definitions): ''contact'', ''account'', ''deal''. '
      'definition_id has a real FK with ON DELETE CASCADE — deleting a field definition '
      'removes all its values automatically. '
      'Orphan cleanup: rows whose record_id no longer exists in the parent entity table '
      'accumulate silently when the entity is deleted. Application must delete custom_field_values '
      'rows alongside entity deletion. See CLAUDE.md — Polymorphic FK Pattern. (MINCRM-510)';
  `);

  pgm.sql(`
    COMMENT ON TABLE notes IS
      'Rich notes attached to CRM entity records, with soft-delete support. '
      'entity_type + entity_id form a polymorphic reference — no FK constraint exists '
      'because PostgreSQL FKs cannot span multiple parent tables. '
      'Valid entity_type values: ''contact'', ''account'', ''deal'', ''lead''. '
      'Soft-deleted rows (deleted_at IS NOT NULL) are excluded from application queries '
      'but remain in the table; the partial GIN index on body_text also excludes them. '
      'Hard orphan cleanup (rows whose entity_id no longer exists) is the application''s '
      'responsibility. Soft-deleted orphans are harmless but may be purged by a periodic '
      'maintenance query. See CLAUDE.md — Polymorphic FK Pattern. (MINCRM-510)';
  `);

  pgm.sql(`
    COMMENT ON TABLE gdpr_deletion_log IS
      'Append-only log of GDPR Art. 17 erasure requests (one row per erased record). '
      'The UNIQUE index on (record_type, record_id) is safe because all record_id values '
      'are UUIDs generated by gen_random_uuid() at row-creation time — re-imports always '
      'receive a new UUID. If deterministic external IDs are ever introduced this constraint '
      'must be revisited. See migration 084 for full rationale. (MINCRM-517) '
      'No FK constraint on record_id — the referenced row is hard-deleted during erasure. '
      'Rows are retained indefinitely by design; orphan cleanup does not apply. '
      'See CLAUDE.md — Polymorphic FK Pattern. (MINCRM-510)';
  `);
};

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.down = (pgm) => {
  pgm.sql(`COMMENT ON TABLE gdpr_deletion_log IS
    'Append-only log of GDPR Art. 17 erasure requests (one row per erased record). '
    'The UNIQUE index on (record_type, record_id) is safe because all record_id values '
    'are UUIDs generated by gen_random_uuid() at row-creation time — re-imports always '
    'receive a new UUID. If deterministic external IDs are ever introduced this constraint '
    'must be revisited. See migration 084 for full rationale. (MINCRM-517)';
  `);
  pgm.sql(`COMMENT ON TABLE notes IS NULL;`);
  pgm.sql(`COMMENT ON TABLE custom_field_values IS NULL;`);
  pgm.sql(`COMMENT ON TABLE attachments IS NULL;`);
};
