/**
 * Barrel export for MiniCRM behaviors.
 *
 * Import from here rather than individual files so that reorganizing
 * behavior files internally does not break callers.
 *
 * MINCRM-130, MINCRM-110, MINCRM-357, MINCRM-367
 */

export {
  login,
  logout,
  changePassword,
  navigateToProtectedPage,
  setPassword,
  loginAsAdmin,
  loginAs,
  getCurrentUser,
  logoutViaApi,
  forgotPassword,
  getDevResetToken,
  loginFromCurrentPage,
  requestPasswordReset,
  resetPassword,
  sessionExpiredBannerVisible,
  navigateToLoginWithSessionExpired,
  navigateToLoginPage,
  submitLoginForm,
  navigateToForgotPasswordPage,
  navigateToSetPasswordPage,
  isSetPasswordTokenInvalid,
  navigateToAdminSettingsGeneralPage,
  getMfaRequiredCheckboxLocator,
  getMfaRequiredSuccessLocator,
} from './auth.behaviors.js';
export type {
  AuthBehaviorContext,
  LoginCredentials,
  LoginResult,
  LogoutResult,
  ChangePasswordCredentials,
  ChangePasswordResult,
  NavigateToProtectedPageResult,
  SetPasswordResult,
  CurrentUser,
  RequestPasswordResetResult,
  ResetPasswordResult,
} from './auth.behaviors.js';

export {
  navigateToContacts,
  navigateToContactsOwnedByMe,
  navigateToContactNotFound,
  waitForContactInList,
  waitForBulkCheckbox,
  clickBulkCheckbox,
  filterContactsByTerm,
  editContact,
  createContactViaUI,
  deleteContactViaUI,
  cancelDeleteContact,
  cancelContactEdit,
  searchContacts,
  contactRowIsVisible,
  openContactCreateForm,
  fillContactCreateForm,
  submitContactCreateFormAndWaitForValidation,
  submitContactCreateForm,
  sortContactsByName,
  bulkReassignContacts,
  bulkDeleteContacts,
  getContactById,
  searchContactsViaApi,
  getContactDeals,
  patchContactAccount,
  deleteContact,
  patchContact,
  listContactsViaApi,
  createContactViaApi,
  navigateToContactDetail,
  clickContactEdit,
  fillContactDetailField,
  saveContact,
  isContactDetailLoaded,
  waitForContactDetailReadMode,
  getContactEditButtonLocator,
  clickNewContact,
  submitContactCreateFormAction,
  clickContactsBulkDelete,
  getContactsConfirmDeleteModalLocator,
  cancelContactsBulkDelete,
  clickContactsBulkReassign,
  getContactsBulkReassignModalLocator,
  cancelContactsBulkReassign,
  isBulkActionBarHidden,
  navigateToContactsDomReady,
  isLoadingIndicatorGone,
  performGdprErasure,
  getContactNameHeadingLocator,
  getContactEmailFieldLocator,
} from './contacts.behaviors.js';
export type {
  ContactsBehaviorContext,
  NavigateToContactsResult,
  ContactChanges,
  EditContactResult,
  CreateContactUIFields,
  CreateContactViaUIResult,
  DeleteContactViaUIResult,
  CancelDeleteContactResult,
  CancelContactEditResult,
  SearchContactsResult,
  ContactRowIsVisibleResult,
  PartialContactUIFields,
  SubmitContactFormValidationResult,
  SortContactsByNameResult,
  ContactRow,
  ContactListRow,
} from './contacts.behaviors.js';

export {
  navigateToAccounts,
  navigateToAccountsOwnedByMe,
  editAccount,
  createAccountViaUI,
  deleteAccountViaUI,
  cancelDeleteAccount,
  cancelAccountEdit,
  searchAccounts,
  getAccountById,
  searchAccountsViaApi,
  listAccountsViaApi,
  deleteAccount,
  createAccountViaApi,
  patchAccount,
  noAlertExists,
  clickAccountEditButton,
  isLinkedContactAbsent,
  navigateToAccountDetail,
  fillAccountDetailField,
  saveAccountDetail,
  isAccountDetailLoaded,
} from './accounts.behaviors.js';
export type {
  AccountsBehaviorContext,
  NavigateToAccountsResult,
  AccountChanges,
  EditAccountResult,
  CreateAccountUIFields,
  CreateAccountViaUIResult,
  DeleteAccountViaUIResult,
  CancelDeleteAccountResult,
  CancelAccountEditResult,
  SearchAccountsResult,
  AccountRow,
  AccountListRow,
} from './accounts.behaviors.js';

export {
  openDeal,
  advanceDealStage,
  closeDealAsWon,
  dragDealToStage,
  getDealById,
  getDealsByAccount,
  linkContactToDeal,
  patchDealStage,
  patchDeal,
  deleteDeal,
  createDealViaApi,
  listDealsViaApi,
  exportDealsAsCsv,
  navigateToPipelineBoard,
  pipelineBoardIsLoaded,
  getPipelineBoardLocator,
  getDealCardLocator,
  getDealStageSelectOnBoardLocator,
  getPipelineBoardStageUpdateErrorLocator,
  getPipelineBoardCloseDealModalLocator,
  cancelCloseDealModal,
  clickNewDealOnBoard,
  getPipelineMobileStageNameLocator,
  navigateToDealDetail,
  openDealEditForm,
  getDealNameInputLocator,
  getDealStageSelectOnFormLocator,
  getDealValueInputLocator,
  getDealCloseDateInputLocator,
  getDealAccountSelectLocator,
  getDealFormSubmitLocator,
  submitDealForm,
  getDealNameHeadingLocator,
  clickDeleteDeal,
  confirmDeleteDeal,
  getDealLinkedContactsHeadingLocator,
  getDealLinkContactSelectLocator,
  getDealLinkContactButtonLocator,
  getDealLinkedContactLocator,
  getDealUnlinkContactLocator,
  getDealLinkedContactsEmptyLocator,
  getDealNotFoundLocator,
  getDealNotFoundBackLink,
  navigateToDealNotFound,
  getDealAttachmentsSectionLocator,
  getDealAttachmentsFileInputLocator,
  getDealAttachmentsListLocator,
  waitForDealsListUrl,
} from './deals.behaviors.js';
export type {
  DealsBehaviorContext,
  OpenDealResult,
  AdvanceDealStageResult,
  CloseDealAsWonResult,
  DragDealToStageResult,
  DealRow,
  DealListRow,
} from './deals.behaviors.js';

export {
  navigateToMyTasks,
  taskIsVisible,
  completeTask,
  showCompletedTasks,
} from './tasks.behaviors.js';
export type {
  TasksBehaviorContext,
  NavigateToMyTasksResult,
  TaskIsVisibleResult,
  CompleteTaskResult,
} from './tasks.behaviors.js';

export {
  navigateToUsers,
  inviteUserViaUI,
  userIsVisibleInList,
  findUserById,
  inviteUserViaApi,
  setUserPassword,
  adminSetUserPassword,
  deactivateUser,
  reactivateUser,
  changeUserRole,
  resetOnboardingViaUI,
  suppressUserOnboarding,
} from './users.behaviors.js';
export type {
  UsersBehaviorContext,
  NavigateToUsersResult,
  InviteUserViaUIResult,
  UserIsVisibleInListResult,
  UserRow,
  InviteUserResponse,
  ResetOnboardingViaUIResult,
} from './users.behaviors.js';

export {
  navigateToLeads,
  navigateToLeadsOwnedByMe,
  createLeadViaUI,
  createLeadViaUIThenCreateAnyway,
  updateLeadStatus,
  showDisqualifiedLeads,
  showConvertedLeads,
  convertLead,
  deleteLead,
  leadRowIsHidden,
  getLeadById,
  createLeadViaApi,
  convertLeadViaApi,
  getLeads,
  disqualifyLead,
  patchLead,
  navigateToLeadDetail,
  clickLeadEdit,
  fillLeadDetailField,
  saveLead,
  isLeadDetailLoaded,
} from './leads.behaviors.js';
export type {
  LeadsBehaviorContext,
  NavigateToLeadsResult,
  CreateLeadUIFields,
  CreateLeadViaUIResult,
  CreateLeadViaUIThenCreateAnywayResult,
  UpdateLeadStatusResult,
  ShowDisqualifiedLeadsResult,
  ShowConvertedLeadsResult,
  ConvertLeadResult,
  DeleteLeadResult,
  LeadRowIsHiddenResult,
  LeadRow,
  LeadListRow,
  LeadConversionResult,
} from './leads.behaviors.js';

export {
  typeSearchQuery,
  typeSearchQueryRaw,
  getSearchResult,
  clickSearchResult,
  getSearchEmptyState,
  getMinLengthHint,
  checkNoResultsForQuery,
  typeSearchQueryAndCheckPanel,
  clearSearchQuery,
  globalSearchViaApi,
} from './search.behaviors.js';
export type {
  SearchBehaviorContext,
  TypeSearchQueryResult,
  GetSearchResultResult,
  ClickSearchResultResult,
  GetSearchEmptyStateResult,
  GetMinLengthHintResult,
  CheckNoResultsForQueryResult,
  TypeSearchQueryAndCheckPanelResult,
  GlobalSearchResult,
} from './search.behaviors.js';

export {
  navigateToAdminTags,
  renameTagViaUI,
  deleteTagViaUI,
  attachTagViaUI,
  detachTagViaUI,
  getTagById,
  getContactTags,
  attachTagToContact,
  getDealTags,
} from './tags.behaviors.js';
export type {
  TagsBehaviorContext,
  NavigateToAdminTagsResult,
  RenameTagViaUIResult,
  DeleteTagViaUIResult,
  AttachTagViaUIResult,
  DetachTagViaUIResult,
  TagRow,
  ContactTagRow,
  DealTagRow,
} from './tags.behaviors.js';

export {
  filterAuditLog,
  getAuditLog,
  getAuditLogRowButtonLocator,
  getAuditLogDetailPanelLocator,
} from './audit-log.behaviors.js';
export type {
  AuditLogBehaviorContext,
  FilterAuditLogResult,
  AuditLogEntry,
} from './audit-log.behaviors.js';

export {
  createNoteViaUI,
  editNoteViaUI,
  deleteNoteViaUI,
  noteCardIsVisible,
  maskedNoteCardIsVisible,
  createNoteViaApi,
  getNoteById,
  listNotes,
  patchNote,
  deleteNote,
  getRecordAuditLog,
} from './notes.behaviors.js';
export type {
  NotesBehaviorContext,
  CreateNoteInput,
  CreateNoteResult,
  EditNoteInput,
  EditNoteResult,
  DeleteNoteResult,
  NoteRow,
  NoteListRow,
  CreateNoteParams,
} from './notes.behaviors.js';

export {
  navigateToProfile,
  getProfilePreferences,
  uncheckAndSavePreference,
  uncheckAllAndSave,
  reloadAndGetProfilePreferences,
  navigateToAdminSettings,
  toggleAdminEmailNotifications,
  patchNotificationPreferences,
  getEmailNotificationsEnabled,
  setEmailNotificationsEnabled,
} from './notifications.behaviors.js';
export type {
  NotificationsBehaviorContext,
  ProfilePreferences,
  NavigateToProfileResult,
  GetProfilePreferencesResult,
  ToggleAndSavePreferenceResult,
  UncheckAllAndSaveResult,
  NavigateToAdminSettingsResult,
  ToggleAdminEmailNotificationsResult,
  NotificationPreferences,
} from './notifications.behaviors.js';

export {
  simulateConcurrentEdit,
  assertConflictModal,
  isConflictModalVisible,
  getConflictModalLocator,
  getConflictModalTitleLocator,
  getConflictSaveResolvedButtonLocator,
  getConflictDiscardButtonLocator,
  clickConflictSaveResolved,
  clickConflictDiscard,
  selectConflictTheirs,
  selectConflictMine,
} from './concurrency.behaviors.js';
export type {
  ConcurrentEditEntityType,
  ConcurrencyBehaviorContext,
  SimulateConcurrentEditResult,
  AssertConflictModalResult,
} from './concurrency.behaviors.js';

export {
  getActivityById,
  getActivities,
  getMyTasks,
  createActivityViaApi,
  patchActivity,
  getOverdueTaskBadgeLocator,
  isOverdueTaskBadgeHidden,
} from './activities.behaviors.js';
export type { ActivityRow, ActivityListRow, CreateActivityParams } from './activities.behaviors.js';

export {
  createWebhookSubscription,
  listWebhookSubscriptions,
  getWebhookDeliveryLogs,
  pollForWebhookDelivery,
  createAutomationRule,
  getCustomFieldDefinitions,
  createCustomFieldDefinition,
  setContactCustomFields,
  setCurrencySettings,
  setUserLanguage,
  setSystemDefaultLanguage,
  setNavLayout,
  setOnboardingCompleted,
  getOnboardingStatus,
  resetUserOnboardingViaApi,
  getSetupChecklistWidgetLocator,
  getSetupChecklistPillLocator,
  dismissSetupChecklist,
  clickSetupChecklistCollapse,
  navigateToDashboardAndWait,
  waitForDashboardHeading,
  isSetupChecklistWidgetHidden,
  isSetupChecklistPillHidden,
  getSetupChecklistTaskListLocator,
  resetPipelineStagesReviewed,
  getCustomFieldsEditGridLocator,
  getCustomFieldDeleteButtonLocator,
  getCustomFieldInputLocator,
  getCustomFieldLabelLocator,
} from './setup.behaviors.js';
export type { OnboardingBehaviorContext, CustomFieldsBehaviorContext } from './setup.behaviors.js';

export {
  ensureSystemDefaults,
  getAdminSettingsHeadingLocator,
  getAdminSettingsSaveLocator,
  getAdminSettingsCurrencySectionLocator,
  getAdminSettingsEmailNotificationsSectionLocator,
  getAdminSettingsWebhookSectionLocator,
  getAdminSettingsWebhookUrlInputLocator,
  getAdminSettingsWebhookSecretRevealLocator,
  getAdminSettingsWebhookSecretValueLocator,
  getAdminSettingsWebhookRowLocator,
  getAdminSettingsWebhookDeleteConfirmLocator,
  clickAdminSettingsWebhookEvent,
  clickAdminSettingsAddWebhook,
  closeAdminSettingsWebhookSecretModal,
  toggleAdminSettingsWebhook,
  clickAdminSettingsDeleteWebhook,
  confirmAdminSettingsDeleteWebhook,
  getAdminSettingsExchangeRatesSectionLocator,
  getAdminSettingsHomeCurrencySelectLocator,
  getAdminSettingsAddCurrencyFormLocator,
  getAdminSettingsAddCurrencyCodeSelectLocator,
  getAdminSettingsAddCurrencyRateInputLocator,
  clickAdminSettingsAddCurrency,
  confirmAdminSettingsAddCurrency,
  saveAdminSettingsExchangeRates,
  getAdminSettingsExchangeRateSaveSuccessLocator,
  getAdminSettingsExchangeRateRowLocator,
  getAdminSettingsCustomFieldsSectionLocator,
  getAdminSettingsCustomFieldsEntitySelectLocator,
  getAdminSettingsAddFieldFormLocator,
  getAdminSettingsAddFieldNameInputLocator,
  getAdminSettingsCustomFieldsFeedbackLocator,
  getAdminSettingsDeleteFieldConfirmLocator,
  clickAdminSettingsAddField,
  submitAdminSettingsAddField,
  getAdminSettingsBrandingFormLocator,
  getAdminSettingsBrandingCompanyNameLocator,
  getAdminSettingsBrandingColorTextLocator,
  getAdminSettingsBrandingFontSelectLocator,
  getAdminSettingsBrandingSaveLocator,
  getAdminSettingsBrandingSaveSuccessLocator,
  getAdminSettingsBrandingResetButtonLocator,
  getAdminSettingsBrandingResetConfirmLocator,
  getAdminSettingsBrandingResetSuccessLocator,
  getPipelineStagesTableLocator,
  getPipelineStageMoveUpLocator,
  getPipelineStageMoveDownLocator,
  getPipelineStagesFeedbackLocator,
  navigateToUrl,
  navigateToAdminSettingsCustomisation,
  navigateToAdminSettingsGeneral,
  clickMoveUpAndWaitForReorder,
  clickMoveDownAndWaitForReorder,
  clickAddPipelineStage,
  fillAddPipelineStageName,
  submitAddPipelineStage,
  waitForPipelineStagesFeedback,
  fillRenamePipelineStage,
  clickDeletePipelineStageConfirm,
  waitForDeleteStageDialog,
  getSsoSectionLocator,
  getSsoProtocolSelectLocator,
  getSsoIdpMetadataUrlInputLocator,
  getSsoEntityIdInputLocator,
  getSsoSaveButtonLocator,
  getSsoEnabledBadgeLocator,
  getSsoDisableButtonLocator,
  getSsoDisableConfirmButtonLocator,
  getSsoSaveSuccessLocator,
  navigateToLoginPageForSso,
  getSsoLoginButtonLocator,
  navigateToAdminSettingsIntegrations,
  navigateToAdminSettingsCurrency,
  getPipelineAddButtonLocator,
  getNewPipelineNameInputLocator,
  getCreatePipelineSubmitLocator,
  getPipelinesFeedbackLocator,
  getPipelineEditButtonLocator,
  getPipelineEditInputLocator,
  getPipelineSaveButtonLocator,
  getPipelineDeleteButtonLocator,
  getPipelineDeleteConfirmLocator,
  getPipelineDeleteConfirmButtonLocator,
  getPipelineStagesPipelineSelectorLocator,
  getPipelineStageRowLocator,
  getPipelineBoardSelectorLocator,
  getPipelineBoardContainerLocator,
  getPipelineStageEditButtonLocator,
  getPipelineStageSaveButtonLocator,
  getPipelineStageDeleteButtonLocator,
} from './settings.behaviors.js';
export type {
  AdminSettingsBehaviorContext,
  PipelineStageReorderEntry,
  StageReorderResult,
} from './settings.behaviors.js';
export type {
  WebhookSubscription,
  WebhookCreateResult,
  WebhookDeliveryLog,
  AutomationRule,
  CreateAutomationRuleParams,
  CustomFieldDefinition,
  CreateCustomFieldDefinitionParams,
  CurrencySettings,
} from './setup.behaviors.js';

export {
  listAttachments,
  deleteAttachment,
  getAttachmentDownloadStatus,
  getAttachmentDownloadLinkLocator,
  isAttachmentRowHidden,
} from './attachments.behaviors.js';
export type { AttachmentRow, AttachmentsBehaviorContext } from './attachments.behaviors.js';

export {
  getWinLossReport,
  navigateToReports,
  getReportsHeadingLocator,
  getReportsTabListLocator,
  getReportsTabListSelectLocator,
  getReportsWinLossTabLocator,
  getReportsActivityTabLocator,
  getReportsStageTrendTabLocator,
  getReportsWinLossHeadingLocator,
  getReportsActivityVolumeHeadingLocator,
  getReportsStageTrendHeadingLocator,
  getReportsLoadingLocator,
  getReportsStageTrendTableLocator,
  getReportsStageTrendEmptyLocator,
  getReportsDaysSelectLocator,
  getReportsDatePresetSelectLocator,
  getReportsCustomStartInputLocator,
  getReportsCustomEndInputLocator,
  getReportsStatCardsLocator,
  getReportsWonCountValueLocator,
  getReportsLostCountValueLocator,
  getReportsWinRateValueLocator,
  navigateToWinLossReport,
  navigateToStageTrendReport,
} from './reports.behaviors.js';
export type { WinLossReport, ReportsBehaviorContext } from './reports.behaviors.js';

export {
  setNavLayoutViaAPI,
  setNavLayoutViaUI,
  openHamburgerMenu,
  closeHamburgerMenuViaBackdrop,
  closeHamburgerMenuViaCloseButton,
  navigateViaNavLink,
  openMobileNav,
  closeMobileNavViaToggle,
  navigateViaMobileNavLink,
  getNavLinkLocator,
  getAdminSectionDividerLocator,
  getHamburgerDrawerLocator,
  getMobileNavDrawerLocator,
  getMenuToggleLocator,
  getMobileNavLinkLocator,
  getMobileLogoutButtonLocator,
  getMobileLanguageSelectLocator,
  getDesktopLanguageSelectLocator,
  reloadCurrentPage,
  navigateBack,
  navigateForward,
  waitForRedirectToDashboard,
  navigateToUrlAndWait,
  isNavLinkHidden,
  waitForNavLink,
  assertNavLinkIsVisible,
  hamburgerDrawerDoesNotExist,
  waitForCssSelector,
  waitForUrl,
  isMobileNavDrawerHidden,
  selectLanguageAndWaitForPatch,
} from './nav.behaviors.js';
export type {
  NavLayout,
  NavBehaviorContext,
  SetNavLayoutResult,
  SetNavLayoutViaUIResult,
  OpenHamburgerMenuResult,
  CloseHamburgerMenuViaBackdropResult,
  CloseHamburgerMenuViaCloseButtonResult,
  NavigateViaNavLinkResult,
  OpenMobileNavResult,
  CloseMobileNavViaToggleResult,
  NavigateViaMobileNavLinkResult,
  BrowserHistoryNavigationResult,
  WaitForRedirectResult,
} from './nav.behaviors.js';

export {
  assertEmptyStateContainerFills,
  resolveTimestampMasks,
  getRecentActivityFeedLocator,
  getDashboardStatCardLocator,
  getDashboardStatCardValueLocator,
  getRecentActivityEntryLocator,
  countElements,
  navigateToContactDetailPage,
  navigateToDealDetailPage,
  navigateToAccountDetailPage,
  navigateToContactsPage,
  navigateToAccountsPage,
  navigateToLeadsPage,
  navigateToTasksPage,
  navigateToPath,
  getDashboardStatCardsLocator,
  getMyTasksHeadingLocator,
  getNewContactButtonLocator,
  getNewAccountButtonLocator,
  getNewLeadButtonLocator,
  getAccountNameHeadingLocator,
} from './layout.behaviors.js';
export type { LayoutBehaviorContext, EmptyStateContainerFillResult } from './layout.behaviors.js';

export {
  applyPseudoLocale,
  reloadAndWait,
  findHardcodedStrings,
  findOverflowingElements,
} from './i18n.behaviors.js';
export type {
  I18nBehaviorContext,
  HardcodedStringFinding,
  OverflowFinding,
} from './i18n.behaviors.js';

export {
  createSequence,
  deleteSequence,
  getSequence,
  createSequenceStep,
  enrollContact,
  unenrollContact,
  getContactEnrollments,
} from './sequences.behaviors.js';
export type { TestSequence, TestSequenceStep, TestEnrollment } from './sequences.behaviors.js';

export { listFeatureFlags, updateFeatureFlag } from './feature-flags.behaviors.js';
export type { TestFeatureFlag } from './feature-flags.behaviors.js';
