/**
 * Barrel export for MiniCRM behaviors.
 *
 * Import from here rather than individual files so that reorganizing
 * behavior files internally does not break callers.
 *
 *
 */

export {
  login,
  logout,
  changePassword,
  navigateToProtectedPage,
  setPassword,
  loginAsAdmin,
  refreshAdminRestSession,
  loginAs,
  getCurrentUser,
  logoutViaApi,
  forgotPassword,
  getDevResetToken,
  loginFromCurrentPage,
  requestPasswordReset,
  resetPassword,
  sessionExpiredBannerVisible,
  navigateToLoginWithSessionExpired,
  navigateToLoginPage,
  submitLoginForm,
  navigateToForgotPasswordPage,
  navigateToSetPasswordPage,
  isSetPasswordTokenInvalid,
  navigateToAdminSettingsGeneralPage,
  waitForMfaRequiredCheckbox,
  isMfaRequiredChecked,
  clickMfaRequiredCheckbox,
  waitForMfaRequiredSuccess,
  expectMfaRequiredSuccessVisible,
} from './auth.behaviors.js';
export type {
  AuthBehaviorContext,
  LoginCredentials,
  LoginResult,
  LogoutResult,
  ChangePasswordCredentials,
  ChangePasswordResult,
  NavigateToProtectedPageResult,
  SetPasswordResult,
  CurrentUser,
  RequestPasswordResetResult,
  ResetPasswordResult,
} from './auth.behaviors.js';

export {
  navigateToContacts,
  navigateToContactsOwnedByMe,
  navigateToContactNotFound,
  waitForContactInList,
  waitForBulkCheckbox,
  clickBulkCheckbox,
  filterContactsByTerm,
  editContact,
  createContactViaUI,
  deleteContactViaUI,
  cancelDeleteContact,
  cancelContactEdit,
  searchContacts,
  contactRowIsVisible,
  openContactCreateForm,
  fillContactCreateForm,
  submitContactCreateFormAndWaitForValidation,
  submitContactCreateForm,
  sortContactsByName,
  bulkReassignContacts,
  bulkDeleteContacts,
  getContactById,
  searchContactsViaApi,
  getContactDeals,
  patchContactAccount,
  deleteContact,
  patchContact,
  listContactsViaApi,
  createContactViaApi,
  navigateToContactDetail,
  clickContactEdit,
  fillContactDetailField,
  saveContact,
  isContactDetailLoaded,
  waitForContactDetailReadMode,
  expectContactEditButtonVisible,
  clickNewContact,
  submitContactCreateFormAction,
  clickContactsBulkDelete,
  waitForContactsConfirmDeleteModal,
  cancelContactsBulkDelete,
  clickContactsBulkReassign,
  waitForContactsBulkReassignModal,
  cancelContactsBulkReassign,
  isBulkActionBarHidden,
  navigateToContactsDomReady,
  isLoadingIndicatorGone,
  performGdprErasure,
  expectContactNameVisible,
  expectContactNameContainsText,
  getContactEmailFieldText,
  navigateToContactsWithOwnerFilter,
  clickMyTeamOwnerFilter,
  clickAllOwnerFilter,
  getContactsPageUrl,
} from './contacts.behaviors.js';
export type {
  ContactsBehaviorContext,
  NavigateToContactsResult,
  ContactChanges,
  EditContactResult,
  CreateContactUIFields,
  CreateContactViaUIResult,
  DeleteContactViaUIResult,
  CancelDeleteContactResult,
  CancelContactEditResult,
  SearchContactsResult,
  ContactRowIsVisibleResult,
  PartialContactUIFields,
  SubmitContactFormValidationResult,
  SortContactsByNameResult,
  ContactRow,
  ContactListRow,
} from './contacts.behaviors.js';

export {
  navigateToAccounts,
  navigateToAccountsOwnedByMe,
  editAccount,
  createAccountViaUI,
  deleteAccountViaUI,
  cancelDeleteAccount,
  cancelAccountEdit,
  searchAccounts,
  getAccountById,
  searchAccountsViaApi,
  listAccountsViaApi,
  deleteAccount,
  createAccountViaApi,
  patchAccount,
  noAlertExists,
  clickAccountEditButton,
  isLinkedContactAbsent,
  navigateToAccountDetail,
  fillAccountDetailField,
  saveAccountDetail,
  isAccountDetailLoaded,
} from './accounts.behaviors.js';
export type {
  AccountsBehaviorContext,
  NavigateToAccountsResult,
  AccountChanges,
  EditAccountResult,
  CreateAccountUIFields,
  CreateAccountViaUIResult,
  DeleteAccountViaUIResult,
  CancelDeleteAccountResult,
  CancelAccountEditResult,
  SearchAccountsResult,
  AccountRow,
  AccountListRow,
} from './accounts.behaviors.js';

export {
  openDeal,
  advanceDealStage,
  closeDealAsWon,
  dragDealToStage,
  getDealById,
  getDealsByAccount,
  linkContactToDeal,
  patchDealStage,
  patchDeal,
  deleteDeal,
  createDealViaApi,
  listDealsViaApi,
  exportDealsAsCsv,
  navigateToPipelineBoard,
  pipelineBoardIsLoaded,
  waitForPipelineBoard,
  expectDealCardVisible,
  waitForDealCardOnBoard,
  selectDealStageOnBoard,
  waitForPipelineBoardStageUpdateError,
  waitForPipelineBoardCloseDealModal,
  cancelCloseDealModal,
  clickNewDealOnBoard,
  waitForPipelineMobileStageName,
  navigateToDealDetail,
  openDealEditForm,
  fillDealNameInput,
  selectDealStageOnForm,
  fillDealValueInput,
  fillDealCloseDateInput,
  selectDealAccount,
  clickDealFormSubmitAndWaitForDetach,
  submitDealForm,
  waitForDealNameHeading,
  expectDealNameHeadingVisible,
  expectDealNameHeadingContainsText,
  expectDealNameHeadingHasText,
  clickDeleteDeal,
  confirmDeleteDeal,
  waitForDealLinkedContactsHeading,
  selectDealLinkContact,
  clickDealLinkContactButton,
  expectDealLinkedContactVisible,
  clickDealUnlinkContact,
  expectDealLinkedContactsEmptyVisible,
  expectDealNotFoundVisible,
  expectDealNotFoundBackLinkVisible,
  navigateToDealNotFound,
  waitForDealAttachmentsSection,
  uploadDealAttachment,
  waitForDealAttachmentsList,
  waitForDealsListUrl,
  navigateToDealsList,
  clickDealsExportPdfAndAwaitResponse,
} from './deals.behaviors.js';
export type {
  DealsBehaviorContext,
  OpenDealResult,
  AdvanceDealStageResult,
  CloseDealAsWonResult,
  DragDealToStageResult,
  DealRow,
  DealListRow,
} from './deals.behaviors.js';

export {
  navigateToMyTasks,
  expectMyTasksListSettled,
  taskIsVisible,
  completeTask,
  showCompletedTasks,
} from './tasks.behaviors.js';
export type {
  TasksBehaviorContext,
  NavigateToMyTasksResult,
  TaskIsVisibleResult,
  CompleteTaskResult,
} from './tasks.behaviors.js';

export {
  navigateToUsers,
  inviteUserViaUI,
  userIsVisibleInList,
  findUserById,
  inviteUserViaApi,
  setUserPassword,
  adminSetUserPassword,
  deactivateUser,
  reactivateUser,
  changeUserRole,
  resetOnboardingViaUI,
  suppressUserOnboarding,
} from './users.behaviors.js';
export type {
  UsersBehaviorContext,
  NavigateToUsersResult,
  InviteUserViaUIResult,
  UserIsVisibleInListResult,
  UserRow,
  InviteUserResponse,
  ResetOnboardingViaUIResult,
} from './users.behaviors.js';

export {
  navigateToLeads,
  navigateToLeadsOwnedByMe,
  createLeadViaUI,
  createLeadViaUIThenCreateAnyway,
  updateLeadStatus,
  showDisqualifiedLeads,
  showConvertedLeads,
  convertLead,
  deleteLead,
  leadRowIsHidden,
  getLeadById,
  createLeadViaApi,
  convertLeadViaApi,
  getLeads,
  disqualifyLead,
  patchLead,
  navigateToLeadDetail,
  clickLeadEdit,
  fillLeadDetailField,
  saveLead,
  isLeadDetailLoaded,
  clickLeadExportPdfAndAwaitResponse,
} from './leads.behaviors.js';
export type {
  LeadsBehaviorContext,
  NavigateToLeadsResult,
  CreateLeadUIFields,
  CreateLeadViaUIResult,
  CreateLeadViaUIThenCreateAnywayResult,
  UpdateLeadStatusResult,
  ShowDisqualifiedLeadsResult,
  ShowConvertedLeadsResult,
  ConvertLeadResult,
  DeleteLeadResult,
  LeadRowIsHiddenResult,
  LeadRow,
  LeadListRow,
  LeadConversionResult,
} from './leads.behaviors.js';

export {
  typeSearchQuery,
  typeSearchQueryRaw,
  getSearchResult,
  clickSearchResult,
  getSearchEmptyState,
  getMinLengthHint,
  checkNoResultsForQuery,
  typeSearchQueryAndCheckPanel,
  clearSearchQuery,
  globalSearchViaApi,
} from './search.behaviors.js';
export type {
  SearchBehaviorContext,
  TypeSearchQueryResult,
  GetSearchResultResult,
  ClickSearchResultResult,
  GetSearchEmptyStateResult,
  GetMinLengthHintResult,
  CheckNoResultsForQueryResult,
  TypeSearchQueryAndCheckPanelResult,
  GlobalSearchResult,
} from './search.behaviors.js';

export {
  navigateToAdminTags,
  renameTagViaUI,
  deleteTagViaUI,
  attachTagViaUI,
  detachTagViaUI,
  getTagById,
  getContactTags,
  attachTagToContact,
  getDealTags,
} from './tags.behaviors.js';
export type {
  TagsBehaviorContext,
  NavigateToAdminTagsResult,
  RenameTagViaUIResult,
  DeleteTagViaUIResult,
  AttachTagViaUIResult,
  DetachTagViaUIResult,
  TagRow,
  ContactTagRow,
  DealTagRow,
} from './tags.behaviors.js';

export {
  filterAuditLog,
  getAuditLog,
  expectAuditLogHeadingVisible,
  expectAuditLogListVisible,
  expectAuditLogPaginationVisible,
  expectAuditLogPaginationPrevDisabled,
  isAuditLogRowButtonVisible,
  clickAuditLogRowButton,
  expectAuditLogDetailPanelVisible,
} from './audit-log.behaviors.js';
export type {
  AuditLogBehaviorContext,
  FilterAuditLogResult,
  AuditLogEntry,
} from './audit-log.behaviors.js';

export {
  createNoteViaUI,
  editNoteViaUI,
  deleteNoteViaUI,
  noteCardIsVisible,
  maskedNoteCardIsVisible,
  createNoteViaApi,
  getNoteById,
  listNotes,
  patchNote,
  deleteNote,
  getRecordAuditLog,
} from './notes.behaviors.js';
export type {
  NotesBehaviorContext,
  CreateNoteInput,
  CreateNoteResult,
  EditNoteInput,
  EditNoteResult,
  DeleteNoteResult,
  NoteRow,
  NoteListRow,
  CreateNoteParams,
} from './notes.behaviors.js';

export {
  navigateToProfile,
  getProfilePreferences,
  uncheckAndSavePreference,
  uncheckAllAndSave,
  reloadAndGetProfilePreferences,
  navigateToAdminSettings,
  toggleAdminEmailNotifications,
  patchNotificationPreferences,
  getEmailNotificationsEnabled,
  setEmailNotificationsEnabled,
} from './notifications.behaviors.js';
export type {
  NotificationsBehaviorContext,
  ProfilePreferences,
  NavigateToProfileResult,
  GetProfilePreferencesResult,
  ToggleAndSavePreferenceResult,
  UncheckAllAndSaveResult,
  NavigateToAdminSettingsResult,
  ToggleAdminEmailNotificationsResult,
  NotificationPreferences,
} from './notifications.behaviors.js';

export {
  simulateConcurrentEdit,
  assertConflictModal,
  isConflictModalVisible,
  isConflictModalTitleVisible,
  isConflictSaveResolvedButtonVisible,
  isConflictDiscardButtonVisible,
  clickConflictSaveResolved,
  clickConflictDiscard,
  selectConflictTheirs,
  selectConflictMine,
} from './concurrency.behaviors.js';
export type {
  ConcurrentEditEntityType,
  ConcurrencyBehaviorContext,
  SimulateConcurrentEditResult,
  AssertConflictModalResult,
} from './concurrency.behaviors.js';

export {
  getActivityById,
  getActivities,
  getMyTasks,
  createActivityViaApi,
  patchActivity,
  waitForMyTaskRow,
  expectOverdueTaskBadgeVisible,
  isOverdueTaskBadgeHidden,
} from './activities.behaviors.js';
export type { ActivityRow, ActivityListRow, CreateActivityParams } from './activities.behaviors.js';

export {
  createWebhookSubscription,
  listWebhookSubscriptions,
  getWebhookDeliveryLogs,
  pollForWebhookDelivery,
  createAutomationRule,
  getCustomFieldDefinitions,
  createCustomFieldDefinition,
  setContactCustomFields,
  setCurrencySettings,
  setUserLanguage,
  setSystemDefaultLanguage,
  setNavLayout,
  setOnboardingCompleted,
  getOnboardingStatus,
  resetUserOnboardingViaApi,
  expectSetupChecklistWidgetVisible,
  expectSetupChecklistPillVisible,
  dismissSetupChecklist,
  clickSetupChecklistCollapse,
  navigateToDashboardAndWait,
  waitForDashboardHeading,
  isSetupChecklistWidgetHidden,
  isSetupChecklistPillHidden,
  expectSetupChecklistTaskListVisible,
  getSetupChecklistTaskListHtml,
  resetPipelineStagesReviewed,
  expectCustomFieldsEditGridVisible,
  clickCustomFieldDeleteButton,
  fillCustomFieldInput,
  expectCustomFieldLabelVisible,
  expectCustomFieldInputVisible,
} from './setup.behaviors.js';
export type { OnboardingBehaviorContext, CustomFieldsBehaviorContext } from './setup.behaviors.js';

export {
  ensureSystemDefaults,
  clickAdminSettingsWebhookEvent,
  clickAdminSettingsAddWebhook,
  closeAdminSettingsWebhookSecretModal,
  toggleAdminSettingsWebhook,
  clickAdminSettingsDeleteWebhook,
  confirmAdminSettingsDeleteWebhook,
  clickAdminSettingsAddCurrency,
  confirmAdminSettingsAddCurrency,
  saveAdminSettingsExchangeRates,
  clickAdminSettingsAddField,
  submitAdminSettingsAddField,
  navigateToUrl,
  navigateToAdminSettingsCustomisation,
  navigateToAdminSettingsGeneral,
  clickMoveUpAndWaitForReorder,
  clickMoveDownAndWaitForReorder,
  clickAddPipelineStage,
  fillAddPipelineStageName,
  submitAddPipelineStage,
  waitForPipelineStagesFeedback,
  fillRenamePipelineStage,
  clickDeletePipelineStageConfirm,
  waitForDeleteStageDialog,
  navigateToLoginPageForSso,
  navigateToAdminSettingsIntegrations,
  navigateToAdminSettingsCurrency,
  waitForStageExitRequirementsUpdated,
  getAiConfig,
  setAiEnabled,
  resetAiSettings,
  restoreAiDefaultsAfterTest,
  resetVisibilitySettings,
  expectAdminSettingsHeadingVisible,
  expectAdminSettingsSaveVisible,
  expectAdminSettingsWebhookSectionVisible,
  fillAdminSettingsWebhookUrl,
  expectAdminSettingsWebhookSecretRevealVisible,
  getAdminSettingsWebhookSecretValue,
  expectAdminSettingsWebhookDeleteConfirmVisible,
  expectAdminSettingsCurrencySectionVisible,
  expectAdminSettingsExchangeRatesSectionVisible,
  selectAdminSettingsHomeCurrency,
  expectAdminSettingsAddCurrencyFormVisible,
  selectAdminSettingsAddCurrencyCode,
  fillAdminSettingsAddCurrencyRate,
  expectAdminSettingsExchangeRateSaveSuccessVisible,
  expectAdminSettingsExchangeRateRowVisible,
  expectAdminSettingsCustomFieldsSectionVisible,
  selectAdminSettingsCustomFieldsEntity,
  expectAdminSettingsAddFieldFormVisible,
  fillAdminSettingsAddFieldName,
  expectAdminSettingsCustomFieldsFeedbackVisible,
  expectAdminSettingsDeleteFieldConfirmVisible,
  clickAdminSettingsDeleteFieldConfirm,
  expectAdminSettingsBrandingFormVisible,
  fillAdminSettingsBrandingCompanyName,
  fillAdminSettingsBrandingColorText,
  selectAdminSettingsBrandingFont,
  clickAdminSettingsBrandingSave,
  expectAdminSettingsBrandingSaveSuccessVisible,
  clickAdminSettingsBrandingReset,
  clickAdminSettingsBrandingResetConfirm,
  expectAdminSettingsBrandingResetSuccessVisible,
  expectPipelineStagesTableVisible,
  expectSsoSectionVisible,
  selectSsoProtocol,
  fillSsoIdpMetadataUrl,
  fillSsoEntityId,
  expectSsoSaveSuccessVisible,
  clickSsoSaveButton,
  expectSsoEnabledBadgeVisible,
  expectSsoEnabledBadgeNotVisible,
  expectSsoDisableConfirmVisible,
  clickSsoDisableButton,
  clickSsoDisableConfirmButton,
  expectSsoLoginButtonVisible,
  expectSsoLoginButtonNotVisible,
  expectFeatureFlagsListVisible,
  clickFeatureFlagConfirmOk,
  expectFeatureFlagToggleChecked,
  expectFeatureFlagToggleUnchecked,
  clickFeatureFlagToggle,
  expectFeatureFlagConfirmDialogVisible,
  expectFeatureFlagConfirmDialogNotVisible,
  expectAdminSettingsAiTabAttached,
  expectAdminSettingsAiTabDisabled,
  expectAdminSettingsAiTabEnabled,
  expectAiSettingsPanelVisible,
  expectAiMasterToggleVisible,
  clickAiMasterToggle,
  expectAiMasterToggleUnchecked,
  expectAiMasterToggleChecked,
  expectAiToggleConfirmDialogVisible,
  expectAiToggleConfirmDialogNotVisible,
  clickAiToggleConfirmButton,
  clickAiToggleConfirmAndWait,
  clickAiToggleCancelButton,
  expectAiDpaCheckboxVisible,
  expectAiDpaCheckboxNotVisible,
  clickAiDpaCheckbox,
  expectAiDpaWarningBannerVisible,
  expectAiDpaWarningBannerNotVisible,
  expectAiDataPostureBadgeVisible,
  expectAiModelSelectVisible,
  expectAiTestConnectionButtonVisible,
  clickAiTestConnectionButton,
  expectAiTestConnectionResultVisible,
  expectPipelineDeleteConfirmVisible,
  waitForPipelineDeleteConfirm,
  expectPipelineDeleteConfirmContainsText,
  selectPipelineBoardPipeline,
  expectPipelineBoardSelectorVisible,
  expectRoleViewButtonVisible,
  clickRoleViewButton,
  expectRoleCapabilityPanelVisible,
  expectRoleCapabilityPanelNotVisible,
  expectRoleCapabilityReadOnlyListVisible,
  expectRoleReadOnlyCapabilityCheckboxDisabled,
  clickPipelineAddButton,
  fillNewPipelineName,
  clickCreatePipelineSubmit,
  expectPipelinesFeedbackVisible,
  clickPipelineEditButton,
  fillPipelineEditInput,
  clickPipelineSaveButton,
  clickPipelineDeleteButton,
  clickPipelineDeleteConfirmButton,
  selectPipelineStagesPipeline,
  expectPipelineStageRowVisible,
  expectPipelineBoardContainerVisible,
  clickPipelineStageEditButton,
  clickPipelineStageSaveButton,
  fillPipelineStageExitRequiredInput,
  expectPipelineStageMoveUpEnabled,
  expectPipelineStageMoveUpDisabled,
  expectPipelineStageMoveDownEnabled,
  clickPipelineStageDeleteButton,
  expectAdminSettingsWebhookRowVisible,
  expectAdminSettingsWebhookRowContainsText,
  expectAdminSettingsWebhookRowNotVisible,
  expectVisibilitySettingsPanelVisible,
  expectVisibilityContactsSelectVisible,
  selectVisibilityContacts,
  clickVisibilitySaveButton,
  expectVisibilitySaveSuccessVisible,
} from './settings.behaviors.js';
export type {
  AdminSettingsBehaviorContext,
  PipelineStageReorderEntry,
  StageReorderResult,
  TestAiConfig,
} from './settings.behaviors.js';
export type {
  WebhookSubscription,
  WebhookCreateResult,
  WebhookDeliveryLog,
  AutomationRule,
  CreateAutomationRuleParams,
  CustomFieldDefinition,
  CreateCustomFieldDefinitionParams,
  CurrencySettings,
} from './setup.behaviors.js';

export {
  listAttachments,
  deleteAttachment,
  getAttachmentDownloadStatus,
  waitForAttachmentDownloadLinkAndGetHref,
  isAttachmentRowHidden,
} from './attachments.behaviors.js';
export type { AttachmentRow, AttachmentsBehaviorContext } from './attachments.behaviors.js';

export {
  getWinLossReport,
  navigateToReports,
  expectReportsHeadingVisible,
  expectReportsTabListVisible,
  expectReportsTabListSelectVisible,
  expectReportsTabListSelectHasValue,
  selectReportsMobileTab,
  expectReportsWinLossTabVisible,
  expectReportsActivityTabVisible,
  clickReportsActivityTab,
  expectReportsStageTrendTabVisible,
  expectReportsWinLossHeadingVisible,
  expectReportsActivityVolumeHeadingVisible,
  expectReportsStageTrendHeadingVisible,
  waitForReportsLoadingHidden,
  isReportsStageTrendTableVisible,
  isReportsStageTrendEmptyVisible,
  selectReportsDays,
  expectReportsDaysSelectHasValue,
  selectReportsDatePreset,
  fillReportsCustomStartInput,
  fillReportsCustomEndInput,
  expectReportsStatCardsVisible,
  getReportsWonCountText,
  getReportsLostCountText,
  expectReportsWinRateVisible,
  getReportsWinRateText,
  navigateToWinLossReport,
  navigateToStageTrendReport,
  reloadPage,
  navigateToCustomReports,
  expectCustomReportsTabVisible,
  expectCustomReportBuilderVisible,
  expectRunReportButtonVisible,
  runCustomReport,
  saveCustomReport,
  waitForSaveDialogClosed,
  waitForSavedReportsList,
  waitForSavedReportByName,
  expectSavedReportByNameVisible,
  clickSavedReportByName,
  getReportsEntityTypeSelectValue,
  navigateToReportsPage,
  clickReportExportPdfAndAwaitResponse,
} from './reports.behaviors.js';
export type { WinLossReport, ReportsBehaviorContext } from './reports.behaviors.js';

export {
  setNavLayoutViaAPI,
  setNavLayoutViaUI,
  openHamburgerMenu,
  closeHamburgerMenuViaBackdrop,
  closeHamburgerMenuViaCloseButton,
  navigateViaNavLink,
  openMobileNav,
  closeMobileNavViaToggle,
  navigateViaMobileNavLink,
  expectNavLinkHasClass,
  expectNavLinkNotHasClass,
  expectNavLinkVisible,
  expectAdminSectionDividerVisible,
  expectHamburgerDrawerVisible,
  expectHamburgerDrawerNotVisible,
  expectMobileNavDrawerVisible,
  expectMobileNavDrawerNotVisible,
  expectMenuToggleVisible,
  focusMenuToggle,
  expectMobileNavLinkVisible,
  expectMobileLogoutButtonVisible,
  expectMobileLanguageSelectVisible,
  getDesktopLanguageSelectLocator,
  reloadCurrentPage,
  navigateBack,
  navigateForward,
  waitForRedirectToDashboard,
  navigateToUrlAndWait,
  isNavLinkHidden,
  waitForNavLink,
  assertNavLinkIsVisible,
  hamburgerDrawerDoesNotExist,
  waitForCssSelector,
  waitForUrl,
  isMobileNavDrawerHidden,
  selectLanguageAndWaitForPatch,
} from './nav.behaviors.js';
export type {
  NavLayout,
  NavBehaviorContext,
  SetNavLayoutResult,
  SetNavLayoutViaUIResult,
  OpenHamburgerMenuResult,
  CloseHamburgerMenuViaBackdropResult,
  CloseHamburgerMenuViaCloseButtonResult,
  NavigateViaNavLinkResult,
  OpenMobileNavResult,
  CloseMobileNavViaToggleResult,
  NavigateViaMobileNavLinkResult,
  BrowserHistoryNavigationResult,
  WaitForRedirectResult,
} from './nav.behaviors.js';

export {
  assertEmptyStateContainerFills,
  resolveTimestampMasks,
  expectRecentActivityFeedVisible,
  getDashboardStatCardValue,
  isRecentActivityEntryVisible,
  countElements,
  navigateToContactDetailPage,
  navigateToDealDetailPage,
  navigateToAccountDetailPage,
  navigateToContactsPage,
  navigateToAccountsPage,
  navigateToLeadsPage,
  navigateToTasksPage,
  navigateToPath,
  waitForDashboardStatCards,
  waitForMyTasksHeading,
  clickOverdueTasksStatCard,
  expectOverdueFilterChipVisible,
  waitForNewContactButton,
  waitForNewAccountButton,
  waitForNewLeadButton,
  waitForAccountNameHeading,
  expectDashboardStatCardVisible,
} from './layout.behaviors.js';
export type { LayoutBehaviorContext, EmptyStateContainerFillResult } from './layout.behaviors.js';

export {
  applyPseudoLocale,
  reloadAndWait,
  findHardcodedStrings,
  findOverflowingElements,
} from './i18n.behaviors.js';
export type {
  I18nBehaviorContext,
  HardcodedStringFinding,
  OverflowFinding,
} from './i18n.behaviors.js';

export {
  createSequence,
  deleteSequence,
  getSequence,
  createSequenceStep,
  enrollContact,
  unenrollContact,
  getContactEnrollments,
} from './sequences.behaviors.js';
export type { TestSequence, TestSequenceStep, TestEnrollment } from './sequences.behaviors.js';

export { listFeatureFlags, updateFeatureFlag } from './feature-flags.behaviors.js';
export type { TestFeatureFlag } from './feature-flags.behaviors.js';

export {
  navigateToAiPage,
  waitForAiConversationPanel,
  waitForAiEmptyState,
  waitForAiSidebarText,
  waitForAiThreadText,
  isAiConversationPanelVisible,
  isAiContextPanelVisible,
  isAiMessageInputVisible,
  isAiSendButtonVisible,
  isAiAddContextButtonVisible,
  isAiEmptyStateVisible,
  sendAiMessageViaUI,
  getAssistantMessageText,
  clickNewSessionButton,
  switchToAiSession,
  getMessageThreadText,
  getSessionSidebarText,
  deleteAiSessionViaUI,
  isAiNavLinkVisible,
  isAiSessionItemVisible,
  createAiSessionViaApi,
  sendAiMessageViaApi,
  getAiSessionViaApi,
  deleteAllAiSessionsViaApi,
} from './ai.behaviors.js';
export type {
  AiBehaviorContext,
  SendAiMessageResult,
  DeleteAiSessionResult,
  AiSessionRow,
  AiMessageRow,
} from './ai.behaviors.js';
